"""Release gate: fail before packaging if any application payload is absent."""
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'installer'))
from installer_core import REQUIRED, VERSION, PACKAGE, sha256, validate_payload
payload = ROOT / 'installer/payload'
# A runtime used during development must not leak generated bytecode into releases.
cached = [p for p in payload.rglob('*') if p.is_file()
          and (p.suffix == '.pyc' or '__pycache__' in p.parts)]
if cached:
    raise SystemExit('RELEASE BLOCKED: remove generated Python caches before packaging: '
                     + str(cached[0]))
for name in REQUIRED:
    if not (payload / name).is_file(): raise SystemExit('RELEASE BLOCKED: missing ' + name)
files = {p.relative_to(payload).as_posix(): {'size': p.stat().st_size, 'sha256': sha256(p)}
         for p in sorted(payload.rglob('*')) if p.is_file() and p != payload / 'manifest.json'}
(payload / 'manifest.json').write_text(json.dumps({'version': VERSION, 'package': PACKAGE, 'files': files}, indent=2), encoding='utf-8')
validate_payload(payload)
print('Validated', len(files), 'bundled files;', round(sum(f['size'] for f in files.values()) / 1048576, 1), 'MiB.')
